plugins {
    id 'java-library'
}

group = 'org.apache.kafka.security'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.bytebuddy:byte-buddy:1.14.18'
    implementation 'net.bytebuddy:byte-buddy-agent:1.14.18'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.jar {
    manifest {
        attributes(
                'Premain-Class': 'org.apache.kafka.security.agent.PolicyAgent',
                'Can-Redefine-Classes': 'true',
                'Can-Retransform-Classes': 'true'
        )
    }
}